In [2]:
import sys
import numpy as np

In [26]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [27]:
b = np.array([0, .5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
a[0], a[1]

(1, 2)

In [29]:
a[0:]

array([1, 2, 3, 4, 5])

In [30]:
a[1:3]

array([2, 3])

In [31]:
a[1:-1]

array([2, 3, 4])

In [32]:
a[::2]

array([1, 3, 5])

In [33]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [34]:
b[[0,2,-1]]

array([0., 1., 2.])

In [35]:
a
a.dtype

dtype('int32')

In [36]:
b
b.dtype

dtype('float64')

In [37]:
a.dtype

dtype('int32')

In [38]:
a = np.array([1,2,3,4,5], dtype = np.float)
a.dtype


dtype('float64')

In [41]:
a

array([0, 1, 2, 3])

In [39]:
b.dtype

dtype('float64')

In [40]:
b = np.array([0, .5, 1, 1.5, 2] , dtype = np.int8)
b.dtype

dtype('int8')

In [42]:
c=np.array(["a", 'b', 'c'])

In [43]:
c.dtype

dtype('<U1')

In [50]:
d = np.array([{'a':15}, sys])

In [51]:
d.dtype

dtype('O')

In [52]:
#Dimentions and Shapes

In [53]:
A = np.array([[1,2,3],[4,5,6]])

In [55]:
A.shape

(2, 3)

In [56]:
A.ndim

2

In [58]:
A.size

6

In [59]:
B = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,13]]])

In [60]:
B.shape

(2, 2, 3)

In [61]:
B.ndim

3

In [62]:
B.size

12

In [63]:
#Indexing & slicing Matices

In [65]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

In [66]:
A[1]

array([4, 5, 6])

In [67]:
A[1][0]

4

In [68]:
A[1,0]

4

In [69]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [72]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [74]:
A[:2, 2:]

array([[3],
       [6]])

In [75]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
A[1] = np.array([10, 11, 12])

In [81]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

In [77]:
A[2] = 99

In [78]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [82]:
#Summany Statistics

In [83]:
a =np.array([1,2,3,4])

In [84]:
a.sum()

10

In [85]:
a.mean()

2.5

In [86]:
a.std()

1.118033988749895

In [87]:
a.var()

1.25

In [89]:
A = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

In [90]:
A.sum()

45

In [91]:
A.mean()

5.0

In [92]:
A.std()

2.581988897471611

In [93]:
A.var()

6.666666666666667

In [95]:
A.sum(axis=0)

array([12, 15, 18])

In [96]:
A.sum(axis=1)

array([ 6, 15, 24])

In [99]:
A.mean(axis=0)

array([4., 5., 6.])

In [101]:
A.mean(axis=1)

array([2., 5., 8.])

In [102]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [103]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [1]:
#Broadcasting and vectot operations

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a+10

array([10, 11, 12, 13])

In [5]:
a*10

array([ 0, 10, 20, 30])

In [6]:
a

array([0, 1, 2, 3])

In [7]:
a+=100

In [8]:
a

array([100, 101, 102, 103])

In [10]:
l = [0,1,2,3]

In [12]:
[i*10 for i in l]

[0, 10, 20, 30]

In [13]:
a = np.arange(4)

In [14]:
a

array([0, 1, 2, 3])

In [15]:
b = np.array([10,10,10,10])

In [16]:
b

array([10, 10, 10, 10])

In [17]:
a+b

array([10, 11, 12, 13])

In [18]:
a*b

array([ 0, 10, 20, 30])

In [19]:
#Boolean arrays

In [20]:
a = np.arange(4)

In [21]:
a

array([0, 1, 2, 3])

In [22]:
a[0],a[-1]

(0, 3)

In [25]:
a[[0,-1]]

array([0, 3])

In [26]:
a[[True, False, False, True]]

array([0, 3])

In [27]:
a>=2

array([False, False,  True,  True])

In [28]:
a[a>=2]

array([2, 3])

In [30]:
a.mean()

1.5

In [31]:
a[a>a.mean()]

array([2, 3])

In [34]:
a[~(a>a.mean())]

array([0, 1])

In [36]:
a[(a<=2)&(a%2==0)]

array([0, 2])

In [37]:
A=np.random.randint(100, size=(3,3))

In [38]:
A

array([[ 1, 81, 89],
       [49, 93, 42],
       [88, 60, 40]])

In [40]:
A[
    np.array([
        [True, False, True],
        [False, True, False],
        [True, False, True]
    ]
    )
]

array([ 1, 89, 93, 88, 40])

In [43]:
A[A>50]

array([81, 89, 93, 88, 60])

In [45]:
#Linear Algebra

In [47]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
B=np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [52]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [53]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [54]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [55]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [57]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [58]:
#Size of objects in Memory

In [60]:
#An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [61]:
sys.getsizeof(10**100)

72

In [62]:
np.dtype(int).itemsize

4

In [63]:
np.dtype(np.int8).itemsize

1

In [67]:
np.dtype(float).itemsize

8

In [68]:
sys.getsizeof([1])

72

In [69]:
np.array([1]).nbytes

4

In [79]:
l=list(range(100000))

In [80]:
a=np.arange(100000)

In [81]:
%time np.sum(a**2)

Wall time: 998 µs


216474736

In [82]:
%time sum([i**2 for i in l])

Wall time: 123 ms


333328333350000

In [83]:
#Useful Numpy Functions

In [3]:
np.random.random(size=2)

array([0.04198522, 0.2075261 ])

In [4]:
np.random.normal(size=2)

array([0.14888084, 0.41838242])

In [6]:
np.random.rand(2,4)

array([[0.96708821, 0.27110784, 0.58760807, 0.63186564],
       [0.2526766 , 0.00683916, 0.27451386, 0.16368819]])